name: quality-assurance

on:
  pull_request:
    branches: [ master ]

jobs:
  qa:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Lint "api" npm package
        run: |
          cd packages/api
          npm run lint

      - name: Lint "common" npm package
        run: |
          cd packages/common
          npm run lint

      - name: Lint "cron" npm package
        run: |
          cd packages/cron
          npm run lint

      - name: Lint "openvpn" npm package
        run: |
          cd packages/openvpn
          npm run lint

      - name: Lint "ui" npm package
        run: |
          cd packages/ui
          npm run lint

      - name: Test "openvpn" npm package
        run: |
          cd packages/openvpn
          npm run test

      - name: Build "api" npm package
        run: |
          cd packages/api
          npm run build

      - name: Build "common" npm package
        run: |
          cd packages/common
          npm run build

      - name: Build "cron" npm package
        run: |
          cd packages/cron
          npm run build

      - name: Build "openvpn" npm package
        run: |
          cd packages/openvpn
          npm run build

      - name: Build "ui" npm package
        run: |
          cd packages/ui
          npm run build
